### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by danielmewes** [bettdouglas/shapely-grpc-io#1]
Hi, what license is this code under?

It might be best to include a `LICENSE` file in the root of the repository to clarify the license and copyright status.

**Comment by bettdouglas** [comment]
@danielmewes I just decided to go with MIT License after reading on https://choosealicense.com/ since it allows anyone to do anything with the code. Let me know your thoughts and if okay, I can merge this PR https://github.com/bettdouglas/shapely-protobuf-io/pull/2

**Comment by danielmewes** [comment]
Sure, MIT license sounds perfect. Thanks so much for open-sourcing this!

**Comment by bettdouglas** [comment]
You're welcome. Can't wait to see what you build with it.
